# Generated by Django 3.1.3 on 2021-07-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210711_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, upload_to='actors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
